export const COMMODITIES_DETAILS_LOADED = 'commodity.COMMODITIES_DETAILS_LOADED';
export const UPDATE_COMMODITIES_DETAILS = 'commodity.UPDATE_COMMODITIES_DETAILS';
export const COMMODITIES_SAVED = 'commodity.COMMODITIES_SAVED';
export const LOAD_COMMODITIES = 'commodity.LOAD_COMMODITIES';
